# include themes/tokyonight/tokyonight_moon.conf
# include themes/dracula/dracula.conf
include themes/rosepine/rose-pine.conf
# include themes/rosepine/rose-pine-moon.conf
# include themes/rosepine/rose-pine-dawn.conf

# fonts
font_family         JetBrainsMonoNL NF Regular
bold_font           JetBrainsMonoNL NF Bold
italic_font         JetBrainsMonoNL NF Italic
bold_italic_font    JetBrainsMonoNL NF Bold Italic

font_size           20

# opacity
background_opacity  0.95

# clipboard
clipboard_control               #blank means off
#
